---
Metrics/BlockLength:
  Exclude:
    - 'lib/**/*.rake'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
