---
AllCops:
  TargetRubyVersion: 2.5

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 15

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
